# Default install options
install_chrony: true
install_vmnotification: true

# Default state for the PTP device
ptp_enabled: false

# Default state for vMotion Notification
vmotion_notifications_enabled: false