# Default install options
install_chrony: true
install_vmnotification: true

# Default state for the PTP device
default_ptp_enabled: false

# Default state for vMotion Notification
default_vmotion_notifications_enabled: false